---
editor_options:
  markdown: 
    wrap: 72
---

MODELING THE GENOTYPE AND PHENOTYPE in ANOPHELES MOSQUITOES IN AFRICA 1- HAPLOID SELECTION PROCESS

We assume the initial observations data are the total number of mosquitoes $Nt$ composed by the number of Anopheles resistant NRt and susceptible NSt at time point t and in location li. And those data are from the bioassay results. NRtili = Ntr Rr, Rr is the reprodcutible rate.

DIPLOID MULTILOCUS MODEL I- Data inputs • WHO discriminating concentration bioassay results from the Vector Atlas database, incorporating data from IR Mapper and WHO Malaria Threats Map. • Vector Atlas data results about genotype frequency • Covariate data : - Modelled use of ITNs 2000-2022 (MAP, see Bertozzi-villa et al. 2021) - Reported coverage of IRS 1997-2022 (WHO/MAP) - Population density 2000-2030 (Worldpop/MAP, adjusted to UN forecasts 2021-2030) - Agricultural intensity of crop production in 2010 (SPAM) Model estimates and projections before/after these covariate year ranges assume covariates are static at earliest/latest year. E.g. for 2023-30 ITNs are set at 2022 estimated levels

II - MODELS DETAILS

1- Observation models:

Bioassay data:

Given data on $N_{i,j}$ and $D_(i,j)$, the observed numbers of mosquitoes tested, and that died,we assume these follow a beta-binomial distribution:

$$
D_{j,i} \sim Betabinomial(N, Q*, \rho)
$$ Where $Q*$ is the modelled population-level susceptibility of the total vector population at the location l= L(i) and time t= L(i) from which this sample of mosquitoes was collected. ρ is an overdispersion term for the insecticide class c=C(j) to which j belongs, capturing the non-independence of individuals selected in the bioassay sample and therefore accounting for the significant variance in susceptibility results from bioassays conducted on different samples of vectors.

Genotype test results for multilocus:

Let $M_z$ be the scaler of number tested and $N_z$ be number positive for genotype $g$ in record Z, where Z is a vector, modeled to represent the population fraction of genotype g at the location and time of sampling. For multiple genotype categories, we use a Dirichlet–Multinomial with mean composition π_zand the same $ρ_z$.

$$
N^{z} \sim DirMultinomial( M^{z}, Z, \rho_z)
$$

Genotype test results for single locus:

We have $N_{lo}^u$ which is the number of mosquitoes positive on genotype, and M is a scaler that contains the number of mosquitoes tested. Assuming HWE with resistant-allele frequency p (so 𝑞= 1−p), the genotype fraction in the population is composed by $(U_{l_0,t}=p_{lo,t}^2, 2p_{lo,t} q_{lo,t}, q_{lo,t}^2)$ and model over-dispersion via a Dirichlet–Multinomial:

$$
N^{u} \sim DirMultinomial (M^{u}, U, \rho_u)
$$
Allele frequency data: We consider $N^{i}$ is the number of mosquitoes tested, and $P_{lo}$ is the allele frequency of the specifi allele $a$ at time point $t$. We will compute $N_{lo,t}^{a}$ which is the number of mosquitoes tested positive to have a defined allele via a Betabinomial likelihood :

$$  
N_{lo,t}^{a} \sim Betabinomial (N^{a}, P_lo, \rho_{a})
$$

Computing phenotype and genotype frequencies:
Computing $Q*$ (fraction of susceptible mosquitoes in the whole population) 
$$ Q_{lo,t}* = \sum_{g=1}^{n} Q_{g}* Z_{g,lo,t}
$$

Computing $Q*$ (fraction of susceptible mosquitoes in the whole population) 

Assuming HWE, $Q_{t}* = 1- P_{t}*$, where $P_{t}^{*}$ is the modeled fraction with the resistant phenotype mosquitoes. To calculate the fraction of resistant phenotype in the population, we will use the fraction of genotype Z, with L and R as indicators variables tied to locus-genotype $g_{lo}$. Thus, L and R will follow a logical number {0 or 1} in depend of the gamete in the genotype $S=1$, $R=0$. According to the Bayes theorem, $$P_{t}^{*} = \Pr(\resistant \phenotype at locus lo)$$ which is equivalent to $$                  P_{t}^{*} = Pr(RR)_{lo} + h*Pr(RS)_{lo} $$ So if we define that in Z (genotype frequency) with two indicators

$$P_{lo, t}^{*} = 1/2 \sum_{g=1}^n Z_{g, t-1}(1-L_{glo})+(1-R_{glo})$$

\<Sylviane to define how we compute $Q*$ (via $P*$) from Z, and how we compute Z from p\>

Allele selection process model:

\<Sylviane to define how we model $p_{t+1,lo,l}$ from $p_{t, lo, l}$ and $w_{t,lo,l}$ and $h_{lo}$

this involves modelling $z_{t+1,g, l}$ from $z_{t,g,l}$, via $r_{g,t,l}$, from $G_{g,lo,t,l}$, from $w_{t,lo,l}$ and $h_{lo}$

but you don't need to redefine how to calculate $z_{t,g,l}$ from $p_{t,lo,l}$ as you have already defined that above \>

To simulate and determine the change of frequencies of genotype and phenotype in one population. This model will use an Bayesian hierarchical semi-mechanistic as described in the IR CUBE model (Golding, 202?). With a determination of the inital fraction of susceptible alleles in one loci at time point t in the population $P_{lo, t}$, to understand the trait of evolution, in which and where the mosquitoes are collected. And we will determine the $P_{lo, t+1}$, the allele frequency at the next step. To get the allele frequency $P_{lo, t+1}$, we need first to determine the genotype frequencies at time point t. We assume that there is no desequilibrum linkage, we define then variables which is the frequency of genotype g at time t, $Z_{g,t}$

Covariate model for single locus genotype relative fitness:

\<Sylviane to add in how we calculate $w_{t, lo, l} = 1 + s_{t, lo, l}$ \>

We model the effect of itns (Xn) use on the frequency of genotype and phenotype on locus lo, by defining the coefficient '$\beta_{lo,k}$' which is the average log selection effect for driver k across insecticides in class scale between 0, 1.and positive selection effects '$γ_{j,k}$' for insecticide j from driver k:''

$$ s = \sum_{k=1} {n} X^{k} \gamma_{k} $$

\<Sylviane to check all subscripts\>
