### Loading Library
library(tidyverse)
library(MCMCpack)
library(coda)
library(greta)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(malariaAtlas)
library(terra)
library(raster)
library(sf)
library(spatialEco)
library(tidyterra)
library(ggdist)
library(greta.dynamics)
